language: go

sudo: false

go:
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/cep21/goverify
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

install:
  - go install -v .

script:
  - goverify -v
  - go run gocoverdir.go

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci
  - cat coverage.out
