language: go

go:
  - 1.3
  - 1.4
  - tip

before_install:
  - go get -u github.com/cep21/goverify
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

install:
  - go get -d -v -t ./... 

script:
  - goverify -v
  - go run gocoverdir.go
  - goveralls -coverprofile=coverage.out -service=travis-ci
  - cat coverage.out
